# Site settings
title: Matt Hancock 
email: not.matt.hancock@gmail.com
description: >
    Math, notes, ramblings, etc
baseurl: ""
url: "http://notmatthancock.github.com" # the base hostname & protocol for your site
github_username: notmatthancock

paginate: 100
paginate_path: "/notes/page/:num"

# Build settings
include: ['_posts']
markdown: kramdown
