# Site settings
title: Matt Hancock 
email: not.matt.hancock@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Math, notes, ramblings, etc
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notmatthancock.github.com" # the base hostname & protocol for your site
github_username: notmatthancock

# Build settings
markdown: kramdown
